<?php
$dictionary['Contact']['fields']['generic_flag'] = array(
    'name' => 'generic_flag',
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'General',
    'save' => true,
    'id_name' => 'rt_cxm_email_contacts_1rt_cxm_email_ida',
    'link' => 'rt_cxm_email_contacts_1',
    'table' => 'rt_cxm_email',
    'module' => 'rt_cxm_email',
    'rname' => 'gflag',
);
$dictionary['Contact']['fields']['facebook_flag'] = array(
    'name' => 'facebook_flag',
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'Facebook',
    'save' => true,
    'id_name' => 'rt_cxm_email_contacts_1rt_cxm_email_ida',
    'link' => 'rt_cxm_email_contacts_1',
    'table' => 'rt_cxm_email',
    'module' => 'rt_cxm_email',
    'rname' => 'fflag',
);
$dictionary['Contact']['fields']['google_flag'] = array(
    'name' => 'google_flag',
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'Google',
    'save' => true,
    'id_name' => 'rt_cxm_email_contacts_1rt_cxm_email_ida',
    'link' => 'rt_cxm_email_contacts_1',
    'table' => 'rt_cxm_email',
    'module' => 'rt_cxm_email',
    'rname' => 'gpflag',
);
$dictionary['Contact']['fields']['twitter_flag'] = array(
    'name' => 'twitter_flag',
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'Twitter',
    'save' => true,
    'id_name' => 'rt_cxm_email_contacts_1rt_cxm_email_ida',
    'link' => 'rt_cxm_email_contacts_1',
    'table' => 'rt_cxm_email',
    'module' => 'rt_cxm_email',
    'rname' => 'tflag',
);
$dictionary['Contact']['fields']['linkedin_flag'] = array(
    'name' => 'linkedin_flag',
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'Linkedin',
    'save' => true,
    'id_name' => 'rt_cxm_email_contacts_1rt_cxm_email_ida',
    'link' => 'rt_cxm_email_contacts_1',
    'table' => 'rt_cxm_email',
    'module' => 'rt_cxm_email',
    'rname' => 'lflag',
);
